on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kicad_version: ["9.0", "9.0.6"]
    name: Test with KiCad ${{ matrix.kicad_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export production files
        id: production
        uses: ./
        if: '!cancelled()'
        with:
          kicad_version: ${{ matrix.kicad_version }}
          kicad_sch: test/test.kicad_sch
          sch_pdf: true
          sch_bom: true
          sch_bom_preset: 'My Preset'
          kicad_pcb: test/test.kicad_pcb
          pcb_gerbers: true
          pcb_image: true

      # Upload production files only if generation succeeded
      - name: Upload production data
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        with:
          name: Production files (KiCad ${{ matrix.kicad_version }})
          path: |
            ${{ github.workspace }}/test/sch.pdf
            ${{ github.workspace }}/test/bom.csv
            ${{ github.workspace }}/test/gbr.zip
            ${{ github.workspace }}/test/images

      - name: Run KiCad ERC with a json output format
        id: erc
        uses: ./
        if: '!cancelled()'
        with:
          kicad_version: ${{ matrix.kicad_version }}
          kicad_sch: test/test.kicad_sch
          sch_erc: true
          report_format: json
          sch_erc_file: erc.json

      - name: Run KiCad DRC
        id: drc
        uses: ./
        if: '!cancelled()'
        with:
          kicad_version: ${{ matrix.kicad_version }}
          kicad_pcb: test/test.kicad_pcb
          pcb_drc: true

      # Upload ERC report only if ERC failed
      - name: Upload ERC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() &&  steps.erc.conclusion == 'failure' }}
        with:
          name: erc.rpt (KiCad ${{ matrix.kicad_version }})
          path: ${{ github.workspace }}/test/erc.rpt

      # Upload DRC report only if DRC failed
      - name: Upload DRC report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.drc.conclusion == 'failure' }}
        with:
          name: drc.rpt (KiCad ${{ matrix.kicad_version }})
          path: ${{ github.workspace }}/test/drc.rpt
